import { Article } from "./articles-service";

export const articles: Map<string, Article> = new Map([
    ["1", {
        referenceId: "1",
        coverPhoto: "rivianvcyber.png",
        title: "Rivian, Cybertruck, and The Cultural Implications of EV Design",
        subtitle: "A conversation with a former Tesla designer on the two vehicles",
        episode: 1,
        body: [
            "The electric truck race has been entertaining to watch from a distance. The industry is tackling complex physical and manufacturing problems. However, probably the most attractive element of this race is the polarizing and bizarrely different nature of the two contending vehicles. On one hand, you have the idiosyncratic cyber-punk Cybertruck from Tesla, and on the other hand, you have the utilitarian solar-punk R1T from Rivian.",
            "Not too long ago, I sat down with an old friend who was a design engineer at Tesla. He was (and still is) a big fan of Tesla and what the company stands for. He is also an incredibly passionate and skilled UI/UX engineer. I enjoy pointing to random advertisements, logos, architectures, etc. and asking him what design strategies or techniques he can spot that do not permeate past my subconscious.",
            "I wanted to know his thoughts between the Cybertruck and the R1T. Even as someone who has the design expertise of a toddler attempting to draw within the lines, I could tell the Cybertruck was somewhat odd. So I asked, \"who are you rooting for?\"",
            "The UI/UX expert drew an analogy for me: the current battle between the two vehicles is reminiscent of the early days between Microsoft and Apple. The two companies were contending for similar markets, yet they had drastically different approaches to design.",
            "The design of the two companies reflected the world they wanted to create. Apple products always seemed to put design and user friendliness first. They wanted to shape a world that was sleek, clean, and a little fun. Their products were always intuitive and simple. They arguably invested more into design and creative software. Meanwhile, Microsoft saw a much more functional world — a world of corporate professionalism. Impressively smooth and powerful tools that also required equally powerful glasses to use.",
            "Both companies were ultimately successful, but it is the design of Apple products that the world chose. It is the design of Apple products that were impressed onto the world. In the corporate environment we now wear eccentric colors and chic outfits instead of oversized brown and khaki suits. Our skyscrapers adopt elegant glass based geometries, while concrete brutalist architecture dies out. We drive sleek aerodynamic cars instead of the blocky cars of the past. Many other technologies, even those of Microsoft, have adopted the design elements of Apple.",
            "Similarly, the former Tesla engineer viewed the two vehicles as separate visions for what the companies wanted the world to be. The Rivian R1T is an adventure vehicle and wants its drivers to go out exploring with it. The car has an array of tires and suspension modes that facilitate driving through harsh terrain. It does not stand out in the wilderness either. The vehicle is designed with natural elements, such as rounded edges, natural soft curves, and Earth tone color palettes.",
            "The inside of the R1T continues to use natural elements through the use of modern wood paneling. The interior also demonstrates the utilitarian and sporty characteristics of the vehicle. In addition to common truck peripherals, such as outlets and additional batteries, the vehicle has built in compartments for a Rivian flash light, portable speaker set, and a whole pullout section for a stove and sink. This truck is meant to be driven into the wilderness and opened with all its doors to the world.",
            "The design of the R1T envisions a world where technology has not strayed from nature. Where even in the cyber enhanced world, we still explore and we still have fun. Our electric trucks are not dainty vehicles that must be reserved to the anthropogenic realm. They can be drudged through the swampy fields of Florida or rough ridden through the deserts of New Mexico. The addition of a portable speaker also sings out to the communal nature of the vehicle. This is a car that we drive with friends, park on the beach and get rowdy with. This is a car that we can make memories with.",
            "The design of the Cybertruck could not scream for an ever more opposite world. The Cybetruck has no smooth edges; it is a polygonal chunk of metal that does not sport a paint coat in its base model. The sharp edges of the truck look like they can cut you just by driving past.",
            "Upon initial inspection, one could possibly mistake the flat bed for an industrial or military vehicle. It would be a gaudy spectacle in any environment outside of an American city. Surrounded by trees in a forest, the truck would look like the left behind engine of an alien spacecraft. In the dense streets of a European city, the oversized truck would feel like a dangerous nuisance to pedestrians and intentionally iconoclastic to the surrounding traditional architecture. Only in the car catered, urban decayed cities of the United States would such a truck seem at home.",
            "Functionally, the vehicle is advertised as tough, for tough people. The Cybertruck is meant to have bulletproof glass windows and a body that can take a hit from a sledge hammer. Similar to Tesla\'s other vehicles, the Cybetruck will sport a “bio defense mode” that will engage an air filter to reduce toxic external particulates. Nothing says tough like a paranoia-inducing armored vehicle in your tranquil suburban neighborhood.",
            "Cybertruck is a post-apocalyptic survival tank, and the design projects a grim future. It\'s a future where we need a tank to drive places, because the world we\'ve made is so inhospitable. Whether it is crime or poor air quality, it envisions a world where one must ask themselves every morning whether it is safe to go outside. The vehicle’s design comes from the cyberpunk genre that inspired grungy futuristic movies like Judge Dredd, Total Recall, and Punisher. These movies are set in dystopian futures where man has allowed technology to get the better of themselves.",
            "After this description, the former Tesla designer expressed, “I don\'t want to live in the world envisioned by the Cybertruck”. As much as he loved Tesla and their broader mission, he was rooting for the Rivian R1T.",
        ]
    }],
    ["2", {
        referenceId: "2",
        coverPhoto: "watch.PNG",
        title: "second blog",
        subtitle: "subtitle",
        episode: 2,
        body: ["paragraph1, paragraph2"]
    }]
])